/**
 * ==========================================================
 * AI Error Analysis System
 * GitHub Actions Summary Generator
 * ==========================================================
 */

import fs from "node:fs";
import path from "node:path";
import { ParsedError } from "./buildLogParser";

const REPORT_DIR = path.join(process.cwd(), "reports");

const SUMMARY_FILE =
  process.env.GITHUB_STEP_SUMMARY ||
  path.join(REPORT_DIR, "github-summary.md");

export function generateGitHubSummary(
  errors: ParsedError[]
): void {

  const lines: string[] = [];

  const critical = count(errors, "CRITICAL");
  const high = count(errors, "HIGH");
  const medium = count(errors, "MEDIUM");
  const low = count(errors, "LOW");

  const buildFailed = critical > 0;

  //-------------------------------------------------------
  // Header
  //-------------------------------------------------------

  lines.push("# 🤖 AI Error Analysis");
  lines.push("");

  lines.push(`Generated : ${new Date().toISOString()}`);
  lines.push("");

  //-------------------------------------------------------
  // Summary
  //-------------------------------------------------------

  lines.push("## 📊 Summary");
  lines.push("");

  lines.push("| Item | Count |");
  lines.push("|------|------:|");
  lines.push(`| Total Errors | ${errors.length} |`);
  lines.push(`| 🔴 Critical | ${critical} |`);
  lines.push(`| 🟠 High | ${high} |`);
  lines.push(`| 🟡 Medium | ${medium} |`);
  lines.push(`| 🔵 Low | ${low} |`);
  lines.push(
    `| Build | ${buildFailed ? "❌ FAILED" : "✅ PASSED"} |`
  );

  lines.push("");

  //-------------------------------------------------------
  // Critical Errors
  //-------------------------------------------------------

  const criticalErrors = errors.filter(
    e => e.severity === "CRITICAL"
  );

  if (criticalErrors.length > 0) {

    lines.push("## 🔥 Critical Errors");
    lines.push("");

    criticalErrors.forEach((error, index) => {

      lines.push(
        `### ${index + 1}. ${error.code ?? "UNKNOWN"}`
      );

      if (error.file) {

        lines.push(
          `**File:** \`${error.file}\``
        );

      }

      if (error.line) {

        lines.push(
          `**Line:** ${error.line}`
        );

      }

      if (error.column) {

        lines.push(
          `**Column:** ${error.column}`
        );

      }

      lines.push(
        `**Message:** ${error.message}`
      );

      lines.push("");

    });

  }

  //-------------------------------------------------------
  // Errors By Source
  //-------------------------------------------------------

  lines.push("## 📂 Errors By Source");
  lines.push("");

  const grouped = groupBySource(errors);

  Object.entries(grouped).forEach(([source, list]) => {

    lines.push(`### ${source}`);

    lines.push("");

    lines.push(`Errors : ${list.length}`);

    lines.push("");

  });

  //-------------------------------------------------------
  // Fix Priority
  //-------------------------------------------------------

  lines.push("## 🚀 Recommended Fix Order");
  lines.push("");

  if (critical > 0) {

    lines.push("1. Fix TypeScript Errors");

  }

  if (
    errors.some(e => e.source === "FIREBASE")
  ) {

    lines.push("2. Fix Firebase Errors");

  }

  if (
    errors.some(e => e.source === "RUNTIME")
  ) {

    lines.push("3. Fix Runtime Errors");

  }

  if (
    errors.some(e => e.source === "ESLINT")
  ) {

    lines.push("4. Fix ESLint Issues");

  }

  lines.push("5. Run Build Again");

  lines.push("");

  //-------------------------------------------------------
  // Footer
  //-------------------------------------------------------

  lines.push("---");

  lines.push("");

  lines.push(
    "Generated by JembeeKart AI Error Analysis"
  );

  fs.writeFileSync(

    SUMMARY_FILE,

    lines.join("\n"),

    "utf8"

  );

}

function count(
  errors: ParsedError[],
  severity: ParsedError["severity"]
): number {

  return errors.filter(
    e => e.severity === severity
  ).length;

}

function groupBySource(
  errors: ParsedError[]
) {

  const result: Record<
    string,
    ParsedError[]
  > = {};

  for (const error of errors) {

    if (!result[error.source]) {

      result[error.source] = [];

    }

    result[error.source].push(error);

  }

  return result;

}
