/**
 * ==========================================================
 * AI Error Analysis System
 * Markdown Report Generator
 * ==========================================================
 */

import fs from "node:fs";
import path from "node:path";
import { ParsedError } from "./buildLogParser";

const REPORT_DIR = path.join(
  process.cwd(),
  "reports"
);

export function generateMarkdownReport(
  errors: ParsedError[]
): void {

  ensureDirectory();

  const critical = count(errors, "CRITICAL");
  const high = count(errors, "HIGH");
  const medium = count(errors, "MEDIUM");
  const low = count(errors, "LOW");

  const lines: string[] = [];

  //----------------------------------------------------------
  // Header
  //----------------------------------------------------------

  lines.push("# AI Error Analysis Report");
  lines.push("");

  lines.push(`Generated : ${new Date().toISOString()}`);
  lines.push("");

  lines.push("---");
  lines.push("");

  //----------------------------------------------------------
  // Summary
  //----------------------------------------------------------

  lines.push("## Summary");
  lines.push("");

  lines.push(`| Item | Value |`);
  lines.push(`|------|------:|`);
  lines.push(`| Total Errors | ${errors.length} |`);
  lines.push(`| Critical | ${critical} |`);
  lines.push(`| High | ${high} |`);
  lines.push(`| Medium | ${medium} |`);
  lines.push(`| Low | ${low} |`);
  lines.push(
    `| Build Status | ${
      critical > 0 ? "❌ FAILED" : "✅ PASSED"
    } |`
  );

  lines.push("");

  //----------------------------------------------------------
  // Error Details
  //----------------------------------------------------------

  lines.push("## Error Details");
  lines.push("");

  if (errors.length === 0) {

    lines.push("No errors found.");

  }

  let index = 1;

  for (const error of errors) {

    lines.push("---");
    lines.push("");

    lines.push(`### ERROR-${String(index).padStart(3, "0")}`);
    lines.push("");

    lines.push(`**Severity:** ${error.severity}`);
    lines.push("");

    if (error.code) {

      lines.push(`**Error Code:** ${error.code}`);
      lines.push("");

    }

    lines.push(
      `**Source:** ${error.source}`
    );

    lines.push("");

    if (error.file) {

      lines.push(
        `**File:** \`${error.file}\``
      );

      lines.push("");

    }

    if (error.line) {

      lines.push(
        `**Line:** ${error.line}`
      );

      lines.push("");

    }

    if (error.column) {

      lines.push(
        `**Column:** ${error.column}`
      );

      lines.push("");

    }

    lines.push("**Message:**");

    lines.push("");

    lines.push("```text");

    lines.push(error.message);

    lines.push("```");

    lines.push("");

    index++;

  }

  //----------------------------------------------------------
  // Footer
  //----------------------------------------------------------

  lines.push("---");

  lines.push("");

  lines.push(
    "Generated by JembeeKart AI Error Analysis System"
  );

  fs.writeFileSync(

    path.join(
      REPORT_DIR,
      "error-analysis.md"
    ),

    lines.join("\n"),

    "utf8"

  );

}

function count(
  errors: ParsedError[],
  severity: ParsedError["severity"]
): number {

  return errors.filter(
    e => e.severity === severity
  ).length;

}

function ensureDirectory(): void {

  if (!fs.existsSync(REPORT_DIR)) {

    fs.mkdirSync(
      REPORT_DIR,
      {
        recursive: true
      }
    );

  }

}
