import { githubRequest } from "./githubClient";

export interface PullRequestResult {
  success: boolean;
  branch: string;
  pullRequestUrl?: string;
}

export async function createPullRequest(): Promise<PullRequestResult> {
  try {
    const branch = `autofix-${Date.now()}`;

    // Get latest commit of main
    const main = await githubRequest("/git/ref/heads/main");

    // Create new branch
    await githubRequest("/git/refs", {
      method: "POST",
      body: JSON.stringify({
        ref: `refs/heads/${branch}`,
        sha: main.object.sha,
      }),
    });

    // Create Pull Request
    const pr = await githubRequest("/pulls", {
      method: "POST",
      body: JSON.stringify({
        title: "🤖 Mission Control Auto Fix",
        head: branch,
        base: "main",
        body: `## Mission Control Auto Fix

This Pull Request was automatically generated by Mission Control.

### Changes
- Applied governance auto fixes
- Updated project files
- Ready for review

Generated automatically by Mission Control.
`,
      }),
    });

    return {
      success: true,
      branch,
      pullRequestUrl: pr.html_url,
    };
  } catch (error) {
    console.error(error);

    return {
      success: false,
      branch: "",
      pullRequestUrl: "",
    };
  }
}
