import { githubRequest } from "./githubClient";
import { uploadModifiedFiles } from "./uploadModifiedFiles";
import { getAutoFixFiles } from "@/mission-control/autofix";

export interface PullRequestResult {
  success: boolean;
  branch: string;
  pullRequestUrl?: string;
  uploadedFiles?: number;
}

export async function createPullRequest(): Promise<PullRequestResult> {
  const branch = `autofix-${Date.now()}`;

  // Get latest commit from main
  const main = await githubRequest("/git/ref/heads/main");

  // Create new branch
  await githubRequest("/git/refs", {
    method: "POST",
    body: JSON.stringify({
      ref: `refs/heads/${branch}`,
      sha: main.object.sha,
    }),
  });

  // Get Auto Fix files
  const { files } = await getAutoFixFiles();

  if (files.length === 0) {
    throw new Error("No files require auto fix.");
  }

  // Upload modified files
  const upload = await uploadModifiedFiles(branch, files);

  // Create Pull Request
  const pr = await githubRequest("/pulls", {
    method: "POST",
    body: JSON.stringify({
      title: "🤖 Mission Control Auto Fix",
      head: branch,
      base: "main",
      body: `## Mission Control Auto Fix

This Pull Request was automatically generated by Mission Control.

### Summary
- Modified Files: ${upload.uploadedFiles}
- Auto Fix applied
- Ready for review

Generated automatically by Mission Control.
`,
    }),
  });

  return {
    success: true,
    branch,
    uploadedFiles: upload.uploadedFiles,
    pullRequestUrl: pr.html_url,
  };
}
