import { githubRequest } from "./githubClient";
import { uploadModifiedFiles } from "./uploadModifiedFiles";
import { generateModifiedFiles } from "@/mission-control/autofix/generateModifiedFiles";

export interface PullRequestResult {
  success: boolean;
  branch: string;
  pullRequestUrl?: string;
  uploadedFiles?: number;
}

export async function createPullRequest(): Promise<PullRequestResult> {
  const branch = `autofix-${Date.now()}`;

  // Get latest main reference
  const main = await githubRequest("/git/ref/heads/main");

  // Create branch
  await githubRequest("/git/refs", {
    method: "POST",
    body: JSON.stringify({
      ref: `refs/heads/${branch}`,
      sha: main.object.sha,
    }),
  });

  // Generate modified files
  const files = generateModifiedFiles();

  if (files.length === 0) {
    throw new Error("No files require auto fix.");
  }

  // Upload files to GitHub
  const upload = await uploadModifiedFiles(
    branch,
    files.map((file) => ({
      path: file.path,
      modifiedContent: file.modifiedContent,
    }))
  );

  // Create Pull Request
  const pr = await githubRequest("/pulls", {
    method: "POST",
    body: JSON.stringify({
      title: "🤖 Mission Control Auto Fix",
      head: branch,
      base: "main",
      body: `## Mission Control Auto Fix

This Pull Request was automatically generated by Mission Control.

### Summary
- Modified Files: ${upload.uploadedFiles}
- Theme fixes applied
- Ready for review

Generated automatically by Mission Control.
`,
    }),
  });

  return {
    success: true,
    branch,
    uploadedFiles: upload.uploadedFiles,
    pullRequestUrl: pr.html_url,
  };
}
