name: AI PR Error Report

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  pull-requests: write

jobs:
  comment:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: error-analysis-report
          path: reports

      - name: Comment PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: reports/error-analysis.md
